version: "3"

services:
  mariadb:
    image: mariadb
    container_name: nplay-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "3307:3306"

  grafana:
    image: grafana/grafana
    container_name: nplay-grafana
    restart: always
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    depends_on:
      - mariadb

  flyway:
    image: redgate/flyway
    container_name: nplay-flyway
    restart: on-failure
    environment:
      FLYWAY_URL: ${MYSQL_URL}
      FLYWAY_USER: ${MYSQL_USER}
      FLYWAY_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-migrations:/db/migration
    command: -locations=filesystem:/db/migration migrate
    depends_on:
      - mariadb

  bot:
    image: ghcr.io/kaktushose/levelbot/nplaybot:latest
    container_name: nplay-bot
    restart: on-failure
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_PRODUCTION: ${BOT_PRODUCTION}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-migrations:/db/migration
      - ./data/logs:/logs
    depends_on:
      - mariadb

  watchtower:
    image: containrrr/watchtower
    container_name: nplay-watchtower
    environment:
      TZ: Europe/Berlin
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_POLL_INTERVAL: 30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db-migrations:
