name: Deploy

on:
  push:
    branches: [ master, dev ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Execute build script via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: bash /home/levelbot/scripts/workflow.sh
